prompt Importing table TIPMOVFLCJA_SAP...
set feedback off
set define off
insert into TIPMOVFLCJA_SAP (TMFCCDGO, TMFCDESC, TMFCINEG)
values (1, 'VENTA DE GAS DOMESTICO', 'I');

insert into TIPMOVFLCJA_SAP (TMFCCDGO, TMFCDESC, TMFCINEG)
values (2, 'VENTA DE GAS INDUSTRIAL', 'I');

insert into TIPMOVFLCJA_SAP (TMFCCDGO, TMFCDESC, TMFCINEG)
values (3, 'VENTA DE GAS COMERCIAL', 'I');

insert into TIPMOVFLCJA_SAP (TMFCCDGO, TMFCDESC, TMFCINEG)
values (4, 'VENTA DE GAS COMERCIALIZACION', 'I');

insert into TIPMOVFLCJA_SAP (TMFCCDGO, TMFCDESC, TMFCINEG)
values (5, 'VENTA DE GAS GNC', 'I');

insert into TIPMOVFLCJA_SAP (TMFCCDGO, TMFCDESC, TMFCINEG)
values (6, 'VENTA DE GAS CEDIDAS', 'I');

insert into TIPMOVFLCJA_SAP (TMFCCDGO, TMFCDESC, TMFCINEG)
values (7, 'CARGO POR CONEXION E INTERNAS CAPITAL', 'I');

insert into TIPMOVFLCJA_SAP (TMFCCDGO, TMFCDESC, TMFCINEG)
values (8, 'CARGO POR CONEXION E INTERNAS INTERESES', 'I');

insert into TIPMOVFLCJA_SAP (TMFCCDGO, TMFCDESC, TMFCINEG)
values (9, 'TRABAJOS VARIOS CAPITAL', 'I');

insert into TIPMOVFLCJA_SAP (TMFCCDGO, TMFCDESC, TMFCINEG)
values (10, 'TRABAJOS VARIOS INTERESES', 'I');

insert into TIPMOVFLCJA_SAP (TMFCCDGO, TMFCDESC, TMFCINEG)
values (11, 'REVISIONES QUINQUENALES', 'I');

insert into TIPMOVFLCJA_SAP (TMFCCDGO, TMFCDESC, TMFCINEG)
values (12, 'CONTRIBUCIONES RECAUDADAS', 'I');

insert into TIPMOVFLCJA_SAP (TMFCCDGO, TMFCDESC, TMFCINEG)
values (13, 'PAGOS MUNDOGAS', 'I');

insert into TIPMOVFLCJA_SAP (TMFCCDGO, TMFCDESC, TMFCINEG)
values (14, 'PERDIDA DE GAS', 'I');

insert into TIPMOVFLCJA_SAP (TMFCCDGO, TMFCDESC, TMFCINEG)
values (15, 'SUBSIDIOS', 'I');

insert into TIPMOVFLCJA_SAP (TMFCCDGO, TMFCDESC, TMFCINEG)
values (16, 'TRANSPORTE DE GAS I', 'I');

insert into TIPMOVFLCJA_SAP (TMFCCDGO, TMFCDESC, TMFCINEG)
values (17, 'CARGO FIJO', 'I');

insert into TIPMOVFLCJA_SAP (TMFCCDGO, TMFCDESC, TMFCINEG)
values (18, 'CARGO POR CONEXION E INTERNAS COMERCIAL CAPITAL', 'I');

insert into TIPMOVFLCJA_SAP (TMFCCDGO, TMFCDESC, TMFCINEG)
values (19, 'CARGO POR CONEXION E INTERNAS COMERCIAL INTERES', 'I');

insert into TIPMOVFLCJA_SAP (TMFCCDGO, TMFCDESC, TMFCINEG)
values (20, 'CARGO POR CONEXION E INTERNAS INDUSTRIAL CAPITAL', 'I');

insert into TIPMOVFLCJA_SAP (TMFCCDGO, TMFCDESC, TMFCINEG)
values (21, 'CARGO POR CONEXION E INTERNAS INDUSTRIAL INTERES', 'I');

insert into TIPMOVFLCJA_SAP (TMFCCDGO, TMFCDESC, TMFCINEG)
values (22, 'KIT GNC CAPITAL', 'I');

insert into TIPMOVFLCJA_SAP (TMFCCDGO, TMFCDESC, TMFCINEG)
values (23, 'KIT GNC INTERESES', 'I');

insert into TIPMOVFLCJA_SAP (TMFCCDGO, TMFCDESC, TMFCINEG)
values (24, 'CREDITO NO BANCARIO', 'I');

insert into TIPMOVFLCJA_SAP (TMFCCDGO, TMFCDESC, TMFCINEG)
values (25, 'FINANCIACION CREDITO NO BANCARIO', 'I');

insert into TIPMOVFLCJA_SAP (TMFCCDGO, TMFCDESC, TMFCINEG)
values (26, 'TRANFERENCIAS DEL FONDO DE SOLIDARIDAD', 'I');

insert into TIPMOVFLCJA_SAP (TMFCCDGO, TMFCDESC, TMFCINEG)
values (27, 'OTROS INGRESOS', 'I');

insert into TIPMOVFLCJA_SAP (TMFCCDGO, TMFCDESC, TMFCINEG)
values (28, 'DESEMBOLSOS DE CREDITOS', 'I');

insert into TIPMOVFLCJA_SAP (TMFCCDGO, TMFCDESC, TMFCINEG)
values (29, 'DESEMBOLSOS DE LEASING', 'I');

insert into TIPMOVFLCJA_SAP (TMFCCDGO, TMFCDESC, TMFCINEG)
values (30, 'INGRESOS FINANCIEROS', 'I');

insert into TIPMOVFLCJA_SAP (TMFCCDGO, TMFCDESC, TMFCINEG)
values (31, 'DIVIDENDOS RECIBIDOS EN EFECTIVO', 'I');

insert into TIPMOVFLCJA_SAP (TMFCCDGO, TMFCDESC, TMFCINEG)
values (32, 'IVA', 'I');

prompt Done.
