prompt Importing table tipmovim_sap...
set feedback off
set define off
insert into tipmovim_sap (TIMVCODI, TIMVIDEN, TIMVDESC, TIMVCONT, TIMVSAEN, TIMVPREC, TIMVISIE, TIMVORDE, TIMVSOPO, TIMVUSO, TIMVFACM, TIMVSURT, TIMVCBOD, TIMVAJUS, TIMVFCNF, TIMVSIGN, TIMVCTBL, TIMVFCJA, TIMVFCAU, TIMVFCIN, TIMVFCEG, TIMVFDOS, TIMVFFAC, TIMVDOCS, TIMVFGEC, TIMVAXGA, TIMVACTI, TIMVCESP, TIMVMANU, TIMVCONP)
values (1503, 'FACT', 'FACTURA CERTIFICACIONES DE INSTALACION', null, null, null, null, null, null, 'G', null, null, null, null, 'N', 'N', 'S', 'N', 'S', 'N', 'N', 'N', 'N', null, 'N', null, 117, null, 'N', 'N');

insert into tipmovim_sap (TIMVCODI, TIMVIDEN, TIMVDESC, TIMVCONT, TIMVSAEN, TIMVPREC, TIMVISIE, TIMVORDE, TIMVSOPO, TIMVUSO, TIMVFACM, TIMVSURT, TIMVCBOD, TIMVAJUS, TIMVFCNF, TIMVSIGN, TIMVCTBL, TIMVFCJA, TIMVFCAU, TIMVFCIN, TIMVFCEG, TIMVFDOS, TIMVFFAC, TIMVDOCS, TIMVFGEC, TIMVAXGA, TIMVACTI, TIMVCESP, TIMVMANU, TIMVCONP)
values (1521, 'FACT', 'FACTURA CONSTRUCCION TRAMOS COMUNES', null, null, null, null, null, null, 'G', null, null, null, null, 'N', 'N', 'S', 'N', 'S', 'S', 'N', 'N', 'N', null, 'N', null, 109, null, 'N', 'N');

insert into tipmovim_sap (TIMVCODI, TIMVIDEN, TIMVDESC, TIMVCONT, TIMVSAEN, TIMVPREC, TIMVISIE, TIMVORDE, TIMVSOPO, TIMVUSO, TIMVFACM, TIMVSURT, TIMVCBOD, TIMVAJUS, TIMVFCNF, TIMVSIGN, TIMVCTBL, TIMVFCJA, TIMVFCAU, TIMVFCIN, TIMVFCEG, TIMVFDOS, TIMVFFAC, TIMVDOCS, TIMVFGEC, TIMVAXGA, TIMVACTI, TIMVCESP, TIMVMANU, TIMVCONP)
values (1526, 'FACT', 'FACTURA TRABAJOS VARIOS SERVICIOS DE CONSTRUCCION', null, null, null, null, null, null, 'G', null, null, null, null, 'N', 'N', 'S', 'N', 'S', 'S', 'N', 'N', 'N', null, 'N', null, 25, null, 'N', 'N');

insert into tipmovim_sap (TIMVCODI, TIMVIDEN, TIMVDESC, TIMVCONT, TIMVSAEN, TIMVPREC, TIMVISIE, TIMVORDE, TIMVSOPO, TIMVUSO, TIMVFACM, TIMVSURT, TIMVCBOD, TIMVAJUS, TIMVFCNF, TIMVSIGN, TIMVCTBL, TIMVFCJA, TIMVFCAU, TIMVFCIN, TIMVFCEG, TIMVFDOS, TIMVFFAC, TIMVDOCS, TIMVFGEC, TIMVAXGA, TIMVACTI, TIMVCESP, TIMVMANU, TIMVCONP)
values (1527, 'FACT', 'FACTURA TRABAJOS VARIOS EXTERNA', null, null, null, null, null, null, 'G', null, null, null, null, 'N', 'N', 'S', 'N', 'S', 'S', 'N', 'N', 'N', null, 'N', null, 112, null, 'N', 'N');

insert into tipmovim_sap (TIMVCODI, TIMVIDEN, TIMVDESC, TIMVCONT, TIMVSAEN, TIMVPREC, TIMVISIE, TIMVORDE, TIMVSOPO, TIMVUSO, TIMVFACM, TIMVSURT, TIMVCBOD, TIMVAJUS, TIMVFCNF, TIMVSIGN, TIMVCTBL, TIMVFCJA, TIMVFCAU, TIMVFCIN, TIMVFCEG, TIMVFDOS, TIMVFFAC, TIMVDOCS, TIMVFGEC, TIMVAXGA, TIMVACTI, TIMVCESP, TIMVMANU, TIMVCONP)
values (313, 'CPPR', 'CONSIGNACIONES POR PUNTOS DE RECAUDOS.', null, null, null, null, null, null, 'B', 'N', null, 'N', 'N', 'N', 'S', 'S', 'S', 'N', 'S', 'N', 'S', 'N', 'VOLANTE DE CONSIGNACION.', 'N', null, null, 'N', 'N', 'N');

insert into tipmovim_sap (TIMVCODI, TIMVIDEN, TIMVDESC, TIMVCONT, TIMVSAEN, TIMVPREC, TIMVISIE, TIMVORDE, TIMVSOPO, TIMVUSO, TIMVFACM, TIMVSURT, TIMVCBOD, TIMVAJUS, TIMVFCNF, TIMVSIGN, TIMVCTBL, TIMVFCJA, TIMVFCAU, TIMVFCIN, TIMVFCEG, TIMVFDOS, TIMVFFAC, TIMVDOCS, TIMVFGEC, TIMVAXGA, TIMVACTI, TIMVCESP, TIMVMANU, TIMVCONP)
values (1560, 'FACT', 'FACTURA CONSTRUCCION DE INTERNAS MULTIFAMILARES', null, null, null, null, null, null, 'G', null, null, null, null, 'N', 'N', 'S', 'N', 'S', 'S', 'N', 'N', 'N', null, 'N', null, 813, null, 'N', null);

insert into tipmovim_sap (TIMVCODI, TIMVIDEN, TIMVDESC, TIMVCONT, TIMVSAEN, TIMVPREC, TIMVISIE, TIMVORDE, TIMVSOPO, TIMVUSO, TIMVFACM, TIMVSURT, TIMVCBOD, TIMVAJUS, TIMVFCNF, TIMVSIGN, TIMVCTBL, TIMVFCJA, TIMVFCAU, TIMVFCIN, TIMVFCEG, TIMVFDOS, TIMVFFAC, TIMVDOCS, TIMVFGEC, TIMVAXGA, TIMVACTI, TIMVCESP, TIMVMANU, TIMVCONP)
values (1567, 'FACT', 'INFO SAP  COSTOS-COSTOS DIFER FACTURA CONSTRUCCION DE INTERNAS MULTIFAMILARES', null, null, null, null, null, null, 'G', null, null, null, null, 'N', 'N', 'S', 'N', 'S', 'S', 'N', 'N', 'N', null, 'N', null, 813, null, 'N', null);

insert into tipmovim_sap (TIMVCODI, TIMVIDEN, TIMVDESC, TIMVCONT, TIMVSAEN, TIMVPREC, TIMVISIE, TIMVORDE, TIMVSOPO, TIMVUSO, TIMVFACM, TIMVSURT, TIMVCBOD, TIMVAJUS, TIMVFCNF, TIMVSIGN, TIMVCTBL, TIMVFCJA, TIMVFCAU, TIMVFCIN, TIMVFCEG, TIMVFDOS, TIMVFFAC, TIMVDOCS, TIMVFGEC, TIMVAXGA, TIMVACTI, TIMVCESP, TIMVMANU, TIMVCONP)
values (527, 'PCMYO', 'COMISIONES POR RECAUDO OLIMPICA', null, null, null, null, null, null, 'B', 'N', null, 'N', 'N', 'N', 'N', 'S', 'S', 'N', 'N', 'S', 'S', 'S', 'No: Factura', 'N', 227, 8888, 'N', 'N', 'N');

insert into tipmovim_sap (TIMVCODI, TIMVIDEN, TIMVDESC, TIMVCONT, TIMVSAEN, TIMVPREC, TIMVISIE, TIMVORDE, TIMVSOPO, TIMVUSO, TIMVFACM, TIMVSURT, TIMVCBOD, TIMVAJUS, TIMVFCNF, TIMVSIGN, TIMVCTBL, TIMVFCJA, TIMVFCAU, TIMVFCIN, TIMVFCEG, TIMVFDOS, TIMVFFAC, TIMVDOCS, TIMVFGEC, TIMVAXGA, TIMVACTI, TIMVCESP, TIMVMANU, TIMVCONP)
values (771, 'NNNN', 'REVERTIR CONSIGNACIONES POR PUNTOS DE RECAUDOS.', null, null, null, null, null, 313, 'B', 'N', null, 'N', 'N', 'N', 'N', 'S', 'S', 'S', 'N', 'S', 'N', 'N', null, 'N', null, null, 'N', 'N', 'N');

prompt Done.
