prompt Importing table FLCJTIPMOV_SAP...
set feedback off
set define off
insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (1, 671, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 312, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 407, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 474, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 535, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 544, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 545, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 546, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 549, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 550, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 551, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 552, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 573, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 575, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 577, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 581, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 587, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 595, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 660, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 662, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 757, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 784, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 868, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 937, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 983, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (28, 862, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (30, 309, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (30, 310, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (30, 311, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (30, 765, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (30, 766, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (30, 767, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (30, 768, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (12, 541, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (26, 630, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (31, 654, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (12, 664, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (24, 801, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (26, 759, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (26, 774, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 785, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 790, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (28, 778, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (28, 802, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (28, 804, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (28, 805, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (28, 806, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (28, 813, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (28, 814, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (28, 956, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (29, 799, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (29, 816, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (29, 817, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (29, 818, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (29, 819, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (29, 820, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (34, 795, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (34, 796, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (34, 797, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (34, 811, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (34, 815, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (34, 822, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (35, 788, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (36, 798, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (36, 836, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (36, 842, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (40, 809, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 319, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (34, 323, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 359, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (29, 388, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (24, 393, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (28, 395, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (28, 403, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (28, 418, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (43, 448, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (36, 543, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 967, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (12, 1003, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (31, 1024, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (36, 1030, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (36, 1033, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 316, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 317, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (26, 318, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (36, 320, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (31, 321, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (36, 322, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (30, 326, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (26, 333, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (29, 337, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (37, 339, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (28, 341, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (36, 343, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (31, 345, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 360, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (26, 364, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (35, 365, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (36, 367, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (29, 370, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 372, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (36, 374, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (36, 376, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (36, 378, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (34, 380, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (34, 382, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (34, 384, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (29, 386, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (36, 390, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (36, 397, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (28, 401, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (40, 415, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (29, 424, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (28, 440, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (34, 441, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (29, 450, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (9, 547, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (9, 548, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (29, 553, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (28, 556, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (29, 557, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 583, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (34, 589, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (42, 590, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (29, 615, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (29, 627, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (42, 628, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (28, 648, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (36, 758, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (29, 760, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (31, 761, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (36, 762, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (36, 763, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (34, 764, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (29, 776, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (37, 777, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (28, 779, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (31, 780, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (26, 787, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (36, 789, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (29, 791, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (36, 792, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (36, 793, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (36, 794, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (41, 800, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (36, 803, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (28, 810, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (36, 826, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (34, 837, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (42, 838, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (29, 849, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (28, 850, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (36, 852, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (36, 854, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (36, 855, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (34, 857, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 931, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 939, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (26, 941, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (42, 980, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (36, 997, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 1004, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (29, 1008, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (29, 1031, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (42, 1032, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (12, 1059, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (12, 1061, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (34, 1063, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (24, 1067, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 1068, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (24, 1071, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (37, 1072, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (34, 1075, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 1076, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (38, 1089, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (38, 1090, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (41, 1097, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (41, 1098, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (34, 1107, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (34, 1108, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (36, 1109, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (31, 1115, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 1117, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 1118, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 1119, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (32, 1121, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (32, 1122, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (29, 1123, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 1138, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (29, 1153, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (29, 1170, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 1173, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (28, 1174, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (32, 1175, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (28, 1176, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (31, 1189, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 1191, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (28, 1254, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (7, 1257, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 1258, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (24, 1302, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (28, 1305, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 1324, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 1325, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (29, 1333, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (29, 1334, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 1364, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 1365, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 1366, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (28, 1368, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (28, 1369, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (36, 1374, 'O', 'I');

insert into FLCJTIPMOV_SAP (FCTMCDGO, FCTMCDTM, FCTMTIPO, FCTMINEG)
values (27, 1386, 'O', 'I');

prompt Done.
